return specific error to user instead of generic error
before:

  error: cannot create filter on table services

after:

  error: error in And header: Cannot combine 2 filters with 'AND': only 1 are on stack